apiVersion: v1
kind: Service
metadata:
  name: parking-detector-app
  namespace: mlops
  labels:
    app: parking-detector
    component: app
spec:
  selector:
    app: parking-detector
    component: app
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
