apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: mlops
  labels:
    app: parking-detector
    component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parking-detector
      component: grafana
  template:
    metadata:
      labels:
        app: parking-detector
        component: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
